version: '3'

services:
   optimizer-app:
      image: slotmachine-optimizer-image
      build:
         context: ./
         dockerfile: Dockerfile
      expose:
         - '8080'
      volumes:
         - /data/optimizer